'use strict';
(()=>{
  const HEADERS=['ChineseWord','Pinyin','PartOfSpeech','ChineseExample','KoreanMeaning','KoreanExample','Category','Chapter','Tags'];
  let accessToken='';
  const api=()=>window.CWordStack;
  const settings=()=>api()?.settings?.()||{};
  function sheetIdFromUrl(v){const s=String(v||'').trim();const m=s.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);if(m)return m[1];if(/^[a-zA-Z0-9-_]{20,}$/.test(s))return s;return''}
  function status(msg){['googleSyncStatus'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=msg})}
  async function requestToken(){return new Promise((resolve,reject)=>{const cfg=settings();if(!cfg.googleClientId)return reject(new Error('설정에서 Google OAuth Client ID를 입력하세요.'));if(!window.google?.accounts?.oauth2)return reject(new Error('Google 로그인 모듈을 아직 불러오지 못했습니다. 잠시 후 다시 시도하세요.'));const client=google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'https://www.googleapis.com/auth/spreadsheets',callback:r=>{if(r.error)reject(new Error(r.error));else{accessToken=r.access_token;resolve(accessToken)}}});client.requestAccessToken({prompt:accessToken?'':'consent'})})}
  async function gfetch(url,opts={}){if(!accessToken)await requestToken();let r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json',...(opts.headers||{})}});if(r.status===401){accessToken='';await requestToken();r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json',...(opts.headers||{})}})}if(!r.ok){let msg='Google Sheets 요청 실패';try{const j=await r.json();msg=j.error?.message||msg}catch{}throw new Error(msg)}if(r.status===204)return null;return r.json()}
  function remoteToCards(values){if(!values?.length)return[];const header=values[0].map(String),idx=Object.fromEntries(HEADERS.map(h=>[h,header.indexOf(h)]));if(idx.ChineseWord<0||idx.KoreanMeaning<0)throw new Error('Flashcards 탭의 헤더가 CWordStack 형식과 다릅니다. CWordStack Excel 양식을 사용하세요.');return values.slice(1).filter(r=>String(r[idx.ChineseWord]||'').trim()).map(r=>api().normalizeCard({chineseWord:r[idx.ChineseWord]||'',pinyin:idx.Pinyin>=0?r[idx.Pinyin]||'':'',partOfSpeech:idx.PartOfSpeech>=0?r[idx.PartOfSpeech]||'':'',chineseExample:idx.ChineseExample>=0?r[idx.ChineseExample]||'':'',koreanMeaning:r[idx.KoreanMeaning]||'',koreanExample:idx.KoreanExample>=0?r[idx.KoreanExample]||'':'',category:idx.Category>=0?r[idx.Category]||'기본 단어장':'기본 단어장',chapter:idx.Chapter>=0?r[idx.Chapter]||'':'',tags:idx.Tags>=0?r[idx.Tags]||'':''}))}
  function rows(cards){return [HEADERS,...cards.map(c=>[c.chineseWord,c.pinyin,c.partOfSpeech,c.chineseExample,c.koreanMeaning,c.koreanExample,c.category,c.chapter,c.tags])]}
  async function sync(){try{const cfg=settings(),sid=sheetIdFromUrl(cfg.googleSheetUrl);if(!sid)throw new Error('설정에서 올바른 Google Sheet URL을 입력하세요.');status('Google Sheet에서 데이터를 읽는 중…');const range=encodeURIComponent('Flashcards!A1:I');const res=await gfetch(`https://sheets.googleapis.com/v4/spreadsheets/${sid}/values/${range}?majorDimension=ROWS`);const remote=remoteToCards(res.values||[]);const st=api().state(),dirty=new Set(st.dirtyKeys||[]),deleted=new Set(st.deletedKeys||[]);const localMap=new Map(st.cards.map(c=>[api().cardKey(c),c]));for(const rc of remote){const k=api().cardKey(rc);if(deleted.has(k))continue;if(!localMap.has(k)||!dirty.has(k))localMap.set(k,{...localMap.get(k),...rc,id:localMap.get(k)?.id||rc.id})}const merged=[...localMap.entries()].filter(([k])=>!deleted.has(k)).map(([,c])=>api().normalizeCard(c));status('병합된 데이터를 Google Sheet에 저장하는 중…');await gfetch(`https://sheets.googleapis.com/v4/spreadsheets/${sid}/values/${encodeURIComponent('Flashcards!A:I')}:clear`,{method:'POST',body:'{}'});const data=rows(merged);await gfetch(`https://sheets.googleapis.com/v4/spreadsheets/${sid}/values/${encodeURIComponent(`Flashcards!A1:I${data.length}`)}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({range:`Flashcards!A1:I${data.length}`,majorDimension:'ROWS',values:data})});st.cards=merged;st.dirtyKeys=[];st.deletedKeys=[];api().persist();api().renderAll();status(`동기화 완료 · ${merged.length}개 카드`);api().toast('Google 동기화를 완료했습니다.')}catch(e){console.error(e);status(`동기화 오류: ${e.message}`);api()?.toast?.(e.message)}}
  for(const id of ['googleSyncBtn','googleSyncBtnCards']){const el=document.getElementById(id);if(el)el.addEventListener('click',sync)}
  window.CWordStackGoogleSync={sync,sheetIdFromUrl};
})();
